from .rol import Rol
from .usuario import Usuario
from .paciente import Paciente
from .doctor import Doctor
from .antecedente import Antecedente
from .paciente_antecedente import PacienteAntecedente
from .imagen import Imagen
from .prediccion import Prediccion
from .historial_clinico import HistorialClinico
from .cita import Cita
from .tipo_tratamiento import TipoTratamiento
from .tratamiento import Tratamiento