from . import rol
from . import usuario
from . import paciente
from . import doctor
from . import antecedente
from . import paciente_antecedente
from . import imagen
from . import prediccion
from . import historial_clinico