from . import rol
from . import usuario
from . import paciente
from . import doctor
from . import enfermedad
from . import paciente_enfermedad
from . import imagen
from . import prediccion
from . import historial_clinico